apiVersion: v2
name: sausage-store
description: Sausage Store semester project
type: application
version: 1.0.0
appVersion: 1.0.0
dependencies:
- name: backend
  version: 1.0.0
  repository: file://charts/backend
- name: backend-report
  version: 1.0.0
  repository: file://charts/backend-report
- name: frontend
  version: 1.0.0
  repository: file://charts/frontend
- name: infra
  version: 1.0.0
  repository: file://charts/infra
