apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-frontend
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "sausage.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicas }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels: {app.kubernetes.io/instance: {{ .Release.Name }}, app.kubernetes.io/component: frontend}
  template:
    metadata:
      labels:
        {{- include "sausage.labels" . | nindent 8 }}
    spec:
      automountServiceAccountToken: false
      securityContext:
        runAsNonRoot: true
        runAsUser: 101
        fsGroup: 101
        seccompProfile: {type: RuntimeDefault}
      containers:
        - name: frontend
          image: "{{ .Values.global.imageRegistry }}/sausage-frontend:{{ .Values.global.imageTag }}"
          imagePullPolicy: IfNotPresent
          ports: [{name: http, containerPort: 8080}]
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities: {drop: [ALL]}

          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          startupProbe:
            httpGet: {path: /healthz, port: http}
            failureThreshold: 60
            periodSeconds: 5
          readinessProbe:
            httpGet: {path: /healthz, port: http}
            periodSeconds: 10
          livenessProbe:
            httpGet: {path: /healthz, port: http}
            periodSeconds: 20
            timeoutSeconds: 3
          volumeMounts:
            - {name: tmp, mountPath: /tmp}
            - {name: nginx, mountPath: /etc/nginx/nginx.conf, subPath: nginx.conf}
      volumes:
        - name: tmp
          emptyDir: {sizeLimit: 128Mi}
        - name: nginx
          configMap: {name: {{ .Release.Name }}-nginx}
