spring.application.name=sausage-store
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.datasource.hikari.maximum-pool-size=5
spring.flyway.enabled=true
spring.flyway.connect-retries=30
spring.cloud.vault.enabled=false
spring.h2.console.enabled=false
management.endpoints.web.exposure.include=health,prometheus
management.endpoint.health.probes.enabled=true
management.metrics.distribution.percentiles-histogram.http.server.requests=true
